{% set version = "1.1.1" %}

package:
  name: gen3users
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gen3users/gen3users-{{ version }}.tar.gz
  sha256: 6636ff127ce145f9104fc72358dd17de54b19be19ae45b89e13876c0adcf4ba0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - gen3users = gen3users.main:main

requirements:
  host:
    - python ={{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - cdislogging >=1.0.0,<2.0.0
    - click
    - pyyaml >=6.0.0,<7.0.0
    - requests

test:
  commands:
    - pip check
    - gen3users --help
  imports:
    - gen3users
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/uc-cdis/gen3users
  summary: Utils for Gen3 Commons user management
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - danielnachun
